using AWBlazorApp.Features.Person.Addresses.Domain; using AWBlazorApp.Features.Person.AddressTypes.Domain; using AWBlazorApp.Features.Person.BusinessEntities.Domain; using AWBlazorApp.Features.Person.BusinessEntityAddresses.Domain; using AWBlazorApp.Features.Person.BusinessEntityContacts.Domain; using AWBlazorApp.Features.Person.ContactTypes.Domain; using AWBlazorApp.Features.Person.CountryRegions.Domain; using AWBlazorApp.Features.Person.EmailAddresses.Domain; using AWBlazorApp.Features.Person.Persons.Domain; using AWBlazorApp.Features.Person.PersonPhones.Domain; using AWBlazorApp.Features.Person.PhoneNumberTypes.Domain; using AWBlazorApp.Features.Person.StateProvinces.Domain; 

namespace AWBlazorApp.Features.Person.EmailAddresses.Dtos;

public sealed record EmailAddressDto(
    int BusinessEntityId, int EmailAddressId, string? EmailAddressValue,
    Guid RowGuid, DateTime ModifiedDate);

public sealed record CreateEmailAddressRequest
{
    public int BusinessEntityId { get; set; }
    public string? EmailAddressValue { get; set; }
}

public sealed record UpdateEmailAddressRequest
{
    public string? EmailAddressValue { get; set; }
}

public static class EmailAddressMappings
{
    public static EmailAddressDto ToDto(this EmailAddress e) => new(
        e.BusinessEntityId, e.EmailAddressId, e.EmailAddressValue, e.RowGuid, e.ModifiedDate);

    public static EmailAddress ToEntity(this CreateEmailAddressRequest r) => new()
    {
        BusinessEntityId = r.BusinessEntityId,
        EmailAddressValue = string.IsNullOrWhiteSpace(r.EmailAddressValue) ? null : r.EmailAddressValue.Trim(),
        RowGuid = Guid.NewGuid(),
        ModifiedDate = DateTime.UtcNow,
        // EmailAddressId is identity-generated by SQL Server.
    };

    public static void ApplyTo(this UpdateEmailAddressRequest r, EmailAddress e)
    {
        if (r.EmailAddressValue is not null)
            e.EmailAddressValue = string.IsNullOrWhiteSpace(r.EmailAddressValue) ? null : r.EmailAddressValue.Trim();
        e.ModifiedDate = DateTime.UtcNow;
    }

    }
