using ElementaryApp.Data.Entities.AdventureWorks;

namespace ElementaryApp.Models.AdventureWorks;

public sealed record EmailAddressDto(
    int BusinessEntityId, int EmailAddressId, string? EmailAddressValue,
    Guid RowGuid, DateTime ModifiedDate);

public sealed record CreateEmailAddressRequest
{
    public int BusinessEntityId { get; set; }
    public string? EmailAddressValue { get; set; }
}

public sealed record UpdateEmailAddressRequest
{
    public string? EmailAddressValue { get; set; }
}

public sealed record EmailAddressAuditLogDto(
    int Id, int BusinessEntityId, int EmailAddressId, string Action,
    string? ChangedBy, DateTime ChangedDate, string? ChangeSummary,
    string? EmailAddressValue, Guid RowGuid, DateTime SourceModifiedDate);

public static class EmailAddressMappings
{
    public static EmailAddressDto ToDto(this EmailAddress e) => new(
        e.BusinessEntityId, e.EmailAddressId, e.EmailAddressValue, e.RowGuid, e.ModifiedDate);

    public static EmailAddress ToEntity(this CreateEmailAddressRequest r) => new()
    {
        BusinessEntityId = r.BusinessEntityId,
        EmailAddressValue = string.IsNullOrWhiteSpace(r.EmailAddressValue) ? null : r.EmailAddressValue.Trim(),
        RowGuid = Guid.NewGuid(),
        ModifiedDate = DateTime.UtcNow,
        // EmailAddressId is identity-generated by SQL Server.
    };

    public static void ApplyTo(this UpdateEmailAddressRequest r, EmailAddress e)
    {
        if (r.EmailAddressValue is not null)
            e.EmailAddressValue = string.IsNullOrWhiteSpace(r.EmailAddressValue) ? null : r.EmailAddressValue.Trim();
        e.ModifiedDate = DateTime.UtcNow;
    }

    public static EmailAddressAuditLogDto ToDto(this EmailAddressAuditLog a) => new(
        a.Id, a.BusinessEntityId, a.EmailAddressId, a.Action, a.ChangedBy, a.ChangedDate,
        a.ChangeSummary, a.EmailAddressValue, a.RowGuid, a.SourceModifiedDate);
}
